### ISSUE TITLE
Add config support for enforcing pointer constraints

### ISSUE THREAD

**Issue by toolCHAINZ** [toolCHAINZ/crackers#7]
For easily synthesizing execve chains, we need a config-based way to assert that a register points to a string.

Obviously, this can be expressed in the callback based post-condition constraint system, but it needs to be expressed in the config file.

Maybe something like:

```toml
[constraint.postcondition.string_ptr]
RDI = "/bin/sh\x00"
```
